#!/bin/bash
python create_affinities.py 1
python create_affinities.py 2
python create_affinities.py 3
python create_affinities.py 4
python create_affinities.py 5
python create_affinities.py 6
python create_affinities.py 7
python create_affinities.py 8
python create_affinities.py 9
python create_affinities.py 10
python create_affinities.py 11
python create_affinities.py 12
python create_affinities.py 13
python create_affinities.py 14
python create_affinities.py 15
python create_affinities.py 16
python create_affinities.py 17
python create_affinities.py 18
python create_affinities.py 19
python create_affinities.py 20
python create_affinities.py 21
python create_affinities.py 22
python create_affinities.py 23
python create_affinities.py 24
python create_affinities.py 25
python create_affinities.py 26
python create_affinities.py 27
python create_affinities.py 28
python create_affinities.py 29
python create_affinities.py 30
python create_affinities.py 31
python create_affinities.py 32
python create_affinities.py 33
python create_affinities.py 34
python create_affinities.py 35
